version: '4.0'

services:
  postgres:
    image: postgres:18
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 05051997
      POSTGRES_DB: michi_academy
    ports:
      - "5435:5435"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:


